---
- hosts: openstack
  gather_facts: no
  become: no

  tasks:
    - name: create keypair for xiaofwan
      openstack.cloud.keypair:
        cloud: rhos-01
        state: present
        name: "xiaofwan"
        public_key_file: "/var/home/xiaofwan/.ssh/id_rsa.pub"

    - name: create keypair for jenkins slave
      openstack.cloud.keypair:
        cloud: rhos-01
        state: present
        name: "jslave_key"
        public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjT6VkfcyzUflY3n95oKIuqAOuCN5bJDBzfu0t62DabzcNjpCuK0fiKyx0B+UiLJJhprXnFmxmSly2vHApdwwIjLd09WRepcG8p6WdUTv3LfKljNf/iZrfaNeEC0+zjxyCxXc5a3ePYYi/cIcYy1sZIwe3/Q+q4LHU/rqN7eTG6RkxJ71wN3jP3lrkTQm/Uc+qIHGR3kGQuY+4ARZg08zEtpM2EWWxDvZJWGlhvYxt86mdKy/ngNxbK4fYaq1DRAhJyFxekEaoGSDE+gADNAxknzoslxpqul530Zk/E+umEIxWlYWWFSXppxRk/g1Ue03FKzJ7/bU1y39iCUsMdGJxMpRktWQAWnr1rfQAltgbyePmbk/sXhjHgkDlvkSRQbGJKZ534jXJJaSPmwnUHq8iKr1dBMLo55qK8aBglj/MZUAq7/Y5354cPze2lLtVrOS4IO3UErNLb+H4AZ+suD5OMjUZ3sP6F2FeA/j7wGxv6yUvrVpT4Quc4SVhJOuDRdU= jslave-psi-openstack"

    - name: create security group jslave_security_group for jenkins slave
      openstack.cloud.security_group:
        cloud: rhos-01
        name: "jslave_security_group"
        state: present
        description: security group for jenkins slave

    - name: permit ssh in security group jslave_security_group
      openstack.cloud.security_group_rule:
        cloud: rhos-01
        security_group: "jslave_security_group"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: create security group debug_vm
      openstack.cloud.security_group:
        cloud: rhos-01
        name: "debug_vm"
        state: present
        description: security group for debug_vm

    - name: permit ssh in security group debug_vm
      openstack.cloud.security_group_rule:
        cloud: rhos-01
        security_group: "debug_vm"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: permit http in security group debug_vm
      openstack.cloud.security_group_rule:
        cloud: rhos-01
        security_group: "debug_vm"
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0

    - name: permit https in security group debug_vm
      openstack.cloud.security_group_rule:
        cloud: rhos-01
        security_group: "debug_vm"
        protocol: tcp
        port_range_min: 443
        port_range_max: 443
        remote_ip_prefix: 0.0.0.0/0

    - name: permit squid proxy in security group debug_vm
      openstack.cloud.security_group_rule:
        cloud: rhos-01
        security_group: "debug_vm"
        protocol: tcp
        port_range_min: 8080
        port_range_max: 8080
        remote_ip_prefix: 0.0.0.0/0

    - name: permit cockpit web in security group debug_vm
      openstack.cloud.security_group_rule:
        cloud: rhos-01
        security_group: "debug_vm"
        protocol: tcp
        port_range_min: 9090
        port_range_max: 9090
        remote_ip_prefix: 0.0.0.0/0
